# Uncomment this line to define a global platform for your project
# Uncomment this line if you're using Swift
# use_frameworks!

platform :ios, '9.0'

target 'ASDKSampleApp' do

pod 'CardIO'
pod 'ASDKCore', :path => "../"
pod 'ASDKUI', :path => "../"

end

post_install do |installer|
  project_path = 'ASDKSampleApp.xcodeproj'
  project = Xcodeproj::Project.open(project_path)
  project.targets.each do |target|
    build_phase = target.build_phases.find { |bp| bp.display_name == '[CP] Copy Pods Resources' }

    if build_phase.present?
      target.build_phases.delete(build_phase)
    end
  end

  project.save(project_path)
end
